WITH DATE_CTE AS (
    SELECT 
        TO_TIMESTAMP(STARTED_AT) AS STARTED_AT,
        DATE(TO_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
        MONTH(TO_TIMESTAMP(STARTED_AT)) AS MONTH_STARTED_AT,
        HOUR(TO_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,
        DAYNAME(TO_TIMESTAMP(STARTED_AT)) AS DAYNAME_STARTED_AT,
        {{DAY_TYPE('STARTED_AT')}} AS DAY_TYPE_STARTED_DT,
        {{ GET_SEASON('STARTED_AT') }} AS STATION_OF_YEAR
    FROM {{ source('DEMO', 'BIKE') }}
)
SELECT 
*
FROM DATE_CTE